Added html and css on Desktop version
Tadessejemal1/portfolio-personal pull request #4
Opened 2022-07-07 19:51 UTC by Tadessejemal1

creat desktop version using media quires
Use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: 768px or wider).
-desktop version looks like the one in the Figma design template 
-In order to lay out the elements on the page use Grid and Flexbox.
-no need to implement any functionality that requires JavaScript.

2022-07-07 22:16 UTC, wuletawwonte requested changes
# Hi @Tadessejemal1 👋🏿👋🏿👋🏿  

Good job so far!
There are some issues that you still need to work on to go to the next project! You have only a few more steps and you are done! 💪 💪 💪 

![giphy](https://user-images.githubusercontent.com/74506933/153382064-ed760a8c-4f4a-48d6-b1f0-1aa9e5135097.gif)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Nice commit history ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

- [ ] Please add more description about your pull request in the details section.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-07 22:16 UTC, wuletawwonte commented on styles.css
>  @media only screen and (max-width: 600px) {
- [ ] Since you developed a `mobile-first` website. All the CSS outside of media query blocks is for the mobile version. I think you don't need to add this media query. Please remove this unnecessary code from your CSS file.

2022-07-07 22:16 UTC, wuletawwonte commented on styles.css
> +  }
- [ ] Please add a gap between the `heading-home` and `card-title` elements. There is a gab in the design and you left no space between these elements. 

![imageedit_3_7352153431](https://user-images.githubusercontent.com/12524453/177878804-23501977-0caa-45f9-9757-f27bdac21eac.jpg)

2022-07-07 22:16 UTC, wuletawwonte commented on index.html
>            <li class="navbar-toggle"><i class="fa fa-bars"></i></li>
- [ ] Please give some margin between the hamburger icon and the edge of the viewport. This icon is almost out of sight. 

![Screen Shot 2022-07-08 at 00 56 47](https://user-images.githubusercontent.com/12524453/177878614-174bd625-8946-47d3-b5ec-da69bb4a990d.png)

2022-07-07 22:16 UTC, wuletawwonte commented on index.html
> -                A daily selection of privately personalized reads; no accounts or
- [ ] Please fix the spacing of these elements. When you work on the desktop version, you should also keep the mobile version intact.
- [ ] Also please make sure there is no horizontal scrolling for different widths of the viewport. 
 
<p align="center">&nbsp;
 
| Mobile Version |   Desktop Version |
| ---------- | ----------- |
 | ![Screen Shot 2022-07-08 at 01 01 37](https://user-images.githubusercontent.com/12524453/177879208-280b834f-7df9-42b8-abe1-273781b54199.png) | ![FireShot Capture 154 - Portfolio - localhost](https://user-images.githubusercontent.com/12524453/177879772-b043694f-313d-41b7-a861-1125c4740ccf.png) |
</p>

2022-07-07 22:16 UTC, wuletawwonte commented on index.html
>                  </div>
- [ ] Kindly make sure this list of technologies looks like the design. And please try to use different images for different projects.

<p align="center">&nbsp;
 
| Figma Design |   Your Project |
| ---------- | ----------- |
 | ![Template 2-Main](https://user-images.githubusercontent.com/12524453/177880175-a28e72ef-d0da-4459-906a-39589cae4948.png) | ![FireShot Capture 155 - Portfolio - localhost](https://user-images.githubusercontent.com/12524453/177880206-cb200df5-447a-4e13-bdb1-7b03944ec7f2.png) |
</p>

2022-07-08 15:35 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] The template use a different font-family than yours. You could use the same font-family to match the template provided by Figma.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 15:35 UTC, leonardodiasb commented on index.html
> +                  </div>
- [ ] As the previous code reviewer mentioned, you should keep the mobile version intact and there is still some overlapping going on in the project cards both in mobile and desktop versions. Kindly fix that.
Your design:
![image](https://user-images.githubusercontent.com/61919617/178024113-cb6f9bf7-3d22-475f-aba0-8ae35bcffbff.png)

2022-07-08 15:35 UTC, leonardodiasb commented on styles.css
>  .img-fluid2 {
- [ ] While you made significant progress fixing your mobile version CSS, there is still a horizontal scroll, probably due to this image width. Kindly fix that.
Your design:
![image](https://user-images.githubusercontent.com/61919617/178023505-2811bcdd-ed57-4cca-afc2-af3539015c86.png)

2022-07-08 20:35 UTC, vickymarz requested changes
Hi @Tadessejemal1 , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 20:35 UTC, vickymarz commented on index.html
> +                      <p class="card-text-portfolio">
- [ ] As the previous code reviewer mentioned, the project texts are overlapping in all the project cards in mobile and desktop versions. It is also adding a visible scroll bar for the texts. I can see you added a fixed height to the styling of the card texts which is causing the text to overlap and also added a scroll bar. Kindly fix that 😄 .

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/178066316-87b3c129-b37d-4ca5-9b30-8b6f70b1658b.png)  | ![image](https://user-images.githubusercontent.com/63473584/178066233-978cb771-5e5d-495a-900d-6ec2c88a0f68.png)  |

2022-07-09 00:57 UTC, vickymarz approved these changes
Hi @Tadessejemal1 , 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 
- 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 07:59 UTC, merged